AUTO_RESUME: true
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
DATA_DIR: ''
GPUS: (0, 1)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 30

DATASET:
  COLOR_RGB: true
  # DATASET: 'COCO_HOE_Dataset'
  DATA_FORMAT: jpg
  FLIP: true
  NUM_JOINTS_HALF_BODY: 8
  PROB_HALF_BODY: 0.5
  TRAIN_ROOT: './coco/'
  VAL_ROOT: './coco/'
  ROT_FACTOR: 45
  SCALE_FACTOR: 0.35
  HOE_SIGMA: 4.0

MODEL:
  INIT_WEIGHTS: true
  USE_FEATUREMAP: true
  NAME: vit
  NUM_JOINTS: 23
  PRETRAINED: 'checkpoints/vit+s-coco.pth'
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 192
  - 256
  HEATMAP_SIZE:
  - 48
  - 64
  SIGMA: 2
LOSS:
  USE_DIFFERENT_JOINTS_WEIGHT: False
  USE_TARGET_WEIGHT: True
TRAIN:
  BATCH_SIZE_PER_GPU: 64
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 80
  OPTIMIZER: adamw
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 170
  - 200
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
TEST:
  BATCH_SIZE_PER_GPU: 64
  COCO_BBOX_FILE: '/path/to/coco/person_detection_results/COCO_val2017_detections_AP_H_56_person.json'
  BBOX_THRE: 1.0
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.2
  MODEL_FILE: 'checkpoints/wholebody-s.pth'
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  USE_GT_BBOX: true
  FLIP_TEST: true
  POST_PROCESS: true
  SHIFT_HEATMAP: true
